<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hgon"
 *
 * Auto generated by Extension Builder 2018-08-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'HGON Template',
    'description' => 'Configuration for hgon.de',
    'category' => 'plugin',
    'author' => 'Maximilian Fäßler',
    'author_email' => 'maximilian@faesslerweb.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'rkw_basics' => '8.7.0-8.7.99',
            'rkw_authors' => '7.6.13-8.7.99',
            'news' => '7.2.0-7.2.99',
            'pb_social' => '1.4.0-1.4.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
