<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hgon"
 *
 * Auto generated by Extension Builder 2018-08-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'HGON Template',
    'description' => 'Configuration for hgon.de',
    'category' => 'plugin',
    'author' => 'Maximilian Fäßler',
    'author_email' => 'maximilian@faesslerweb.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '13.4.2',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-13.4.99',
            'news' => '7.2.0-14.0.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
