TYPO3:
  CMS:
    Form:
      persistenceManager:
        allowedExtensionPaths:
          10: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/'
        allowSaveToExtensionPaths: true
        allowDeleteFromExtensionPaths: true
      prototypes:
        ### PROTOTYPE: STANDARD
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                templateRootPaths:
                  100: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Templates/'
                partialRootPaths:
                  100: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Partials/'
                layoutRootPaths:
                  100: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Layouts/'
                translation:
                  translationFile:
                    # Default translation file for the frontend:
                    10: 'EXT:form/Resources/Private/Language/locallang.xlf'
                    # Load your own translation file(s) as desired:
                    20: 'EXT:hgon_template/Resources/Private/Language/FormGeneral.xlf'
            Text:
              properties:
                elementClassAttribute: 'input'
            Textarea:
              properties:
                elementClassAttribute: 'textarea'
          finishersDefinition:
            Confirmation:
              options:
                templateName: 'Confirmation'
                templateRootPaths:
                  10: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Templates/Finishers/Confirmation/'