TYPO3:
  CMS:
    Form:
      persistenceManager:
        allowSaveToExtensionPaths: false
        allowDeleteFromExtensionPaths: false
      prototypes:
        ### PROTOTYPE: STANDARD
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                templateRootPaths:
                  100: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Templates/'
                partialRootPaths:
                  100: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Partials/'
                  110: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Custom/Partials/'
                  # currently does not work for emails: https://wiki.sebkln.de/doku.php?id=typo3:form
                  #120: 'EXT:hgon_template/Resources/Private/Extension/HgonTemplate/Partials/'
                layoutRootPaths:
                  100: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Layouts/'
                  # currently does not work for emails: https://wiki.sebkln.de/doku.php?id=typo3:form
                  #110: 'EXT:hgon_template/Resources/Private/Extension/HgonTemplate/Layouts/'
                translationFiles:
                  # Default form translations are supplied by EXT:form.
                  20: 'EXT:hgon_template/Resources/Private/Language/FormGeneral.xlf'
            Text:
              properties:
                elementClassAttribute: 'input'
            Textarea:
              properties:
                elementClassAttribute: 'textarea'
            ImageUpload:
              properties:
                elementClassAttribute: 'ext-form-img'
            DonationElement:
              __inheritances:
                10: 'TYPO3.CMS.Form.prototypes.standard.formElementsDefinition.Fieldset'
              implementationClassName: 'HGON\HgonTemplate\FormElements\DonationElement'
              properties:
                elementClassAttribute: 'donation-value-container'
          finishersDefinition:
            EmailToReceiver:
              options:
                templateName: 'Default'
                templateRootPaths:
                  150: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Templates/Finishers/Email/'
                partialRootPaths:
                  150: 'EXT:hgon_template/Resources/Private/Extension/HgonTemplate/Partials/'
                layoutRootPaths:
                  150: 'EXT:hgon_template/Resources/Private/Extension/HgonTemplate/Layouts/'
            EmailToSender:
              options:
                templateName: 'Default'
                templateRootPaths:
                  150: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Templates/Finishers/Email/'
                partialRootPaths:
                  150: 'EXT:hgon_template/Resources/Private/Extension/HgonTemplate/Partials/'
                layoutRootPaths:
                  150: 'EXT:hgon_template/Resources/Private/Extension/HgonTemplate/Layouts/'
            Confirmation:
              options:
                templateName: 'Confirmation'
                templateRootPaths:
                  10: 'EXT:hgon_template/Resources/Private/Extension/FormFramework/Frontend/Templates/Finishers/Confirmation/'
