services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  HGON\HgonTemplate\Domain\Repository\:
    resource: '../Classes/Domain/Repository/*'
    autowire: true
    autoconfigure: true

  HGON\HgonTemplate\Controller\:
    resource: '../Classes/Controller/*'
    autowire: true
    autoconfigure: true

  HGON\HgonTemplate\Service\:
    resource: '../Classes/Service/*'
    autowire: true
    autoconfigure: true

  DERHANSEN\SfEventMgt\Service\NotificationService:
    class: HGON\HgonTemplate\Service\SfEventMgtNotificationService
    autowire: true
    autoconfigure: true

  HGON\HgonTemplate\Updates\:
    resource: '../Classes/Updates/*'

  HGON\HgonTemplate\Updates\HgonTemplateTypoScriptConditionMigration:
    tags:
      - name: 'install.upgradewizard'
        identifier: 'hgonTemplateTypoScriptConditionMigration'

  HGON\HgonTemplate\EventListener\SfEventMgtListFilterVariablesListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-list-filter-variables'
        event: DERHANSEN\SfEventMgt\Event\ModifyListViewVariablesEvent

  HGON\HgonTemplate\EventListener\SfEventMgtDetailVariablesListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-detail-variables'
        event: DERHANSEN\SfEventMgt\Event\ModifyDetailViewVariablesEvent

  HGON\HgonTemplate\EventListener\SfEventMgtRegistrationCulinaryVariablesListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-registration-culinary-variables'
        event: DERHANSEN\SfEventMgt\Event\ModifyRegistrationViewVariablesEvent

  HGON\HgonTemplate\EventListener\SfEventMgtRegistrationFormVariablesListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-registration-form-variables'
        event: DERHANSEN\SfEventMgt\Event\ModifyRegistrationViewVariablesEvent

  HGON\HgonTemplate\EventListener\SfEventMgtRegistrationCulinaryValidationListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-registration-culinary-validation'
        event: DERHANSEN\SfEventMgt\Event\ModifyRegistrationValidatorResultEvent

  HGON\HgonTemplate\EventListener\SfEventMgtRegistrationCulinaryPriceListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-registration-culinary-price'
        event: DERHANSEN\SfEventMgt\Event\ModifyRegistrationPriceEvent

  HGON\HgonTemplate\EventListener\SfEventMgtRegistrationCulinaryPersistListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-registration-culinary-persist'
        event: DERHANSEN\SfEventMgt\Event\AfterRegistrationSavedEvent

  HGON\HgonTemplate\EventListener\SfEventMgtRegistrationCulinaryDependingRegistrationsListener:
    autowire: true
    tags:
      - name: event.listener
        identifier: 'hgon-template/sfeventmgt-registration-culinary-depending-registrations'
        event: DERHANSEN\SfEventMgt\Event\ModifyCreateDependingRegistrationsEvent
